### ISSUE TITLE
Failed to upload photo index: 1370, response: 502

### ISSUE THREAD

**Issue by joshinils** [kartaview/upload-scripts#108] opened 2021-05-03 18:13 UTC
I uploaded a bunch of images over night via my raspberry pi and my nas, during which i got this multiple times:
```
 22%|████████████████████████████████████                                                                                                                                | 8831/40115 [4:33:40<18:03:46,  2.08s/it]Failed to upload photo index: 1370, response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>

 22%|████████████████████████████████████▋                                                                                                                                | 8927/40115 [4:36:30<9:19:32,  1.08s/it]    
```
[...]
```
 24%|████████████████████████████████████████▏                                                                                                                           | 9816/40115 [5:04:24<14:55:51,  1.77s/it]Failed to upload photo index: 15, response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
```
[...]
```
99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 39834/40115 [20:24:56<06:10,  1.32s/it]Failed to upload photo index: 7299, response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>

100%|█████████████████████████████████████████████████████████████████████████████████████████████
```

Does that mean it failed to upload a single image? 
Do I have to repeat those sequences where those are contained?

**Comment by Strubbl** [comment] 2021-05-03 18:39
I also get some of these server errors when uploading. Unfortunately you cannot just restart the upload and the files, which were not uploaded due to the server error, are uploaded again. 
Except deleting the stream and the txt files and doing a really fresh new upload i do not know a solution. But that is not real solution because the not uploaded files are way too less to initiate a complete new stream upload. And of course some other files will fail to upload again

**Comment by joshinils** [comment] 2021-05-04 03:31
also, i have the images sorted in some folders, i do not know exactly which failed

**Comment by salabogdan** [comment] 2022-10-31 08:26
This was a bug that happened during a backend update, and should no longer reproduce  so I will close it. Still the underlining issue remains this script should have a better upload progress tracking. Not sure what would be the best approach here since in some cases having the txt file is convenient, one could manually edit the file to finalise a upload or skip a file and so on.

**Closed by salabogdan** 2022-10-31 08:26 UTC
